In [1]:
import numpy as np

in native python, lists exist, numpy uses numpy arrays treated as vector
for example *2 on a list duplicates a list but on vector *2 doubles every element

In [2]:
my_list = [1,2,3,4]
my_list=my_list*2
print(my_list)

array=np.array([1,2,3,4])
array=array*2
print(array)
print(type(array))

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]
<class 'numpy.ndarray'>


arrays can be multidimensional

In [3]:
array0=np.array('A')
array1=np.array(['A','B','C'])
array2=np.array([['A','B','C'],['D','E','F'],['G','H','I']])
array3=np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                 [['J','K','L'],['M','N','O'],['P','Q','R']],
                 [['S','T','U'],['V','W','X'],['Y','Z','0']]])

print(array0.ndim, array1.ndim, array2.ndim, array3.ndim)
print(array3.shape)

0 1 2 3
(3, 3, 3)


normal python uses chain indexing ie array[0][0][0]
numpy uses multidimensional indexing

In [4]:
print(array3[0,0,1]+array3[1,1,2]+array3[0,0,1])

BOB


slicing
array[start:end:step]

In [5]:
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(array[0:4:2]) #same as array[::2}
print(array[:,0:4]) #selecting all columns
print(array[:2,:2]) #first quadrant

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[1 2]
 [5 6]]


scalar arithmetic

In [6]:
array=np.array([1,2,3])
print(array+1)
print(array*3)

[2 3 4]
[3 6 9]


In [7]:
array=np.array([1,2,3])
print(np.sqrt(array))
array=np.array([1.01,2.5,3.99])
print(np.round(array)) #for always rounding down use floor for up use ceil
print(np.pi) #give pi

[1.         1.41421356 1.73205081]
[1. 2. 4.]
3.141592653589793


boolean arrays

In [10]:
scores=np.array([91,55,100,73,82,64])
print(scores>=60)
scores[scores<60]=0
print(scores)

[ True False  True  True  True  True]
[ 91   0 100  73  82  64]


broadcasting

allows numpy to perform operations on arrays with different shapes by virtually expanding dimensions so they match the larger array's shape

when matching dimensions
1) dimensions are either same number
2) one of them is a one

In [12]:
array1=np.array([[1,2,3,4]])
array2=np.array([[1],[2],[3],[4]])

print(array1.shape)
print(array2.shape)

(1, 4)
(4, 1)


they are broadcastable (one of them is a one)


In [13]:
print(array1*array2)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


aggregate functions

summarize data and typically return a single value

In [15]:
array=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(np.sum(array))
print(np.mean(array))
print(np.std(array)) #standard deviation
print(np.var(array)) #variance
#also has max,min; argmin,argmax (position of min,max vals)

print(np.sum(array,axis=0)) #0=column 1=rows

55
5.5
2.8722813232690143
8.25
[ 7  9 11 13 15]


filtering

In [18]:
ages=np.array([[21,17,19,20,16,30,18,65],[39,22,15,99,18,19,21,23]])
adults=np.where(ages>=18, ages, np.nan) #to retain original shape (condition, array, build)

print(adults)

[[21. nan 19. 20. nan 30. 18. 65.]
 [39. 22. nan 99. 18. 19. 21. 23.]]


random numbers

In [ ]:
rng=np.random.default_rng() #set (seed=x) to reproduce same results

print(rng.integers(low=1,high=101,size=(3,2))) #2d array of random no. between 1 to 100


[[35 13]
 [39 69]
 [50 96]]


In [20]:
print(np.random.uniform(low=-1,high=1,size=3)) #for floats

[-0.92399907 -0.34965173  0.40694122]


In [24]:
array=np.array([1,2,3,4])
rng.shuffle(array) #shuffle
num=rng.choice(array) #random select
print(array)
print(num)

[3 4 1 2]
3
